#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_WS GPIO_NUM_5
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_7
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_4

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_17
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_16
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_0

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_WIDTH    320
#define DISPLAY_HEIGHT   240
#define DISPLAY_SWAP_XY  false
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_INVERT_COLOR  false

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_1
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false


// Pin Definitions 
#define LCD_NUM_CS GPIO_NUM_NC
#define LCD_NUM_DC GPIO_NUM_18
#define LCD_NUM_RD GPIO_NUM_NC
#define LCD_NUM_WR GPIO_NUM_8
#define LCD_NUM_RST GPIO_NUM_NC

#define GPIO_LCD_D0 GPIO_NUM_2
#define GPIO_LCD_D1 GPIO_NUM_43
#define GPIO_LCD_D2 GPIO_NUM_44
#define GPIO_LCD_D3 GPIO_NUM_42
#define GPIO_LCD_D4 GPIO_NUM_41
#define GPIO_LCD_D5 GPIO_NUM_40
#define GPIO_LCD_D6 GPIO_NUM_39
#define GPIO_LCD_D7 GPIO_NUM_38
#define GPIO_LCD_D8 GPIO_NUM_11
#define GPIO_LCD_D9 GPIO_NUM_12
#define GPIO_LCD_D10 GPIO_NUM_13
#define GPIO_LCD_D11 GPIO_NUM_14
#define GPIO_LCD_D12 GPIO_NUM_21
#define GPIO_LCD_D13 GPIO_NUM_47
#define GPIO_LCD_D14 GPIO_NUM_48
#define GPIO_LCD_D15 GPIO_NUM_45

/* SD Card */
#define GPIO_SD_SPI_SCLK GPIO_NUM_46
#define GPIO_SD_SPI_MOSI GPIO_NUM_9
#define GPIO_SD_SPI_MISO GPIO_NUM_3
#define GPIO_SD_SPI_CS   GPIO_NUM_10

#endif // _BOARD_CONFIG_H_
